// Generated by CoffeeScript 1.5.0
(function() {

  window.Itch = {};

  Itch.attachBuyButton = function(el, opts) {
	var domain, height, left, top, width;

	if (opts == null) {
		opts = {};
	}

	domain = opts.domain || "itch.io";
	width = opts.width || 650;
	height = opts.height || 400;
	top = (screen.height - height) / 2;
	left = (screen.width - width) / 2;

	if (!opts.user) {
		throw new Error("Missing user");
	}

	if (!opts.game) {
		throw new Error("Missing game");
	}

	return el.onclick = function() {

		if($('#PaypalButton').hasClass('Locked')) {	return false; }
		if(!$('#PaypalButton').hasClass('LoggedIn')) { return false; }

		var w;
		w = window.open("http://" + opts.user + "." + domain + "/" + opts.game + "/purchase", "purchase", "resizable=no, scrollbars=no, width=" + width + ", height=" + height + ", top=" + top + ", left=" + left);
		if (typeof w.focus === "function") {
			w.focus();
		}

		w.onload = function() {
			var PriceField = w.querySelectorAll(".money_input");
			PriceField = PriceField[0];
			PriceField.value = $('#PriceField').val();
		}
	
		return false;
	};
};

}).call(this);

function isNumber(n) {
  return !isNaN(parseFloat(n)) && isFinite(n);
}

$(document).ready(function() {

	var changeLastValue = $('#PriceField').val();
	var lastValue = "";
	var n = NaN;

	$('#PriceField').on('input', function() {

		if($('#PriceField').val() != changeLastValue) {

			var s = $('#PriceField').val().replace(/[^\d.-]/g, '');

			if($('#PriceField').val() != "" && (s != $('#PriceField').val() || !isNumber(s))) {

				$('#PriceField').val(changeLastValue);
			}
			else { changeLastValue = $('#PriceField').val(); }
		}
	});

	$('input#PriceField').focus(function() {
		// turn on timer
		startTimer();
	}).blur(function() {
		// turn off timer
		endTimer();
	});

	checkInputChange = function() {

		if($('#ResponseField').hasClass('black')) { $('#ResponseField').removeClass('Black'); }

		if( $('input#PriceField').val() != lastValue ) {

			n = parseFloat($('input#PriceField').val());
			
			if(n < 4.99) {

				if($('#ResponseField').hasClass('Green')) { $('#ResponseField').removeClass('Green'); }
				if(!$('#ResponseField').hasClass('Red')) { $('#ResponseField').addClass('Red'); }
				if(!$('#PaypalButton').hasClass('Locked')) { $('#PaypalButton').addClass('Locked'); }
				if(!$('input#PriceField').hasClass('Red')) { $('input#PriceField').addClass('Red'); }

				if(n <= 0) {
					$('#ResponseField').html('Oh come on, at least add a positive number');
				}
				else {
					$('#ResponseField').html('That\'s just mean :(');
				}
			}
			else if(n >= 4.99) {

				if($('#ResponseField').hasClass('Red')) { $('#ResponseField').removeClass('Red'); }
				if(!$('#ResponseField').hasClass('Green')) { $('#ResponseField').addClass('Green'); }
				if($('#PaypalButton').hasClass('Locked')) { $('#PaypalButton').removeClass('Locked'); }
				if($('input#PriceField').hasClass('Red')) { $('input#PriceField').removeClass('Red'); }

				if(n == 4.99) {
					$('#ResponseField').html('');
				}
				else if(n < 4.99) {
					$('#ResponseField').html('That\'s just mean :(');
				}
				else if(n < 10) {
					$('#ResponseField').html('Oh, a donation, generous!');
				}
				else if(n < 15) {
					$('#ResponseField').html('Thanks! This is awesome');
				}
				else if(n < 20) {
					$('#ResponseField').html('YOU are awesome');
				}
				else if(n < 50) {
					$('#ResponseField').html('There should be more people in this world like you');
				}
				else if(n < 100) {
					$('#ResponseField').html('I wanna personally high five you');
				}
				else if(n < 200) {
					$('#ResponseField').html('That\'s a lot of money!');
				}
				else if(n < 300) {
					$('#ResponseField').html('You\'re bluffing');
				}
				else if(n < 400) {
					$('#ResponseField').html('Now you are just increasing it to see what I say next');
				}
				else if(n < 500) {
					$('#ResponseField').html('Well I\'m not playing this game anymore');
				}
				else if(n < 600) {
					$('#ResponseField').html('Keep trying, you are not getting anything from me');
				}
				else if(n < 700) {
					$('#ResponseField').html('This is getting out of hand');
				}
				else if(n < 800) {
					$('#ResponseField').html('I dare you to press "buy"');
				}
				else if(n < 900) {
					$('#ResponseField').html('At this rate we\'re gonna go over 9000');
				}
				else if(n < 1000) {
					$('#ResponseField').html('Who would\'ve thought a game price could have it\'s own personality');
				}
				else {
					$('#ResponseField').html('We hope you\'re having a nice day, Mr. Bill Gates');
				}
			}

			lastValue = $('input#Location').val();
		}
	}

	startTimer = function() {
		timer = setInterval(checkInputChange, 1000); // check input field every 200 ms (1/5 sec)
	}

	endTimer = function() {
		checkInputChange();
		clearInterval(timer);
	}

	$("#PaypalButton").click(function(e) {
		if(!$('#PaypalButton').hasClass('Locked')) {
			if($('#PaypalButton').hasClass('LoggedIn')) {
				if(!$('#PaypalButton').hasClass('Loading')) { $('#PaypalButton').addClass('Loading'); }
			} else { e.stopPropagation(); turnOffLight('LoginBox'); }
		}
	});

	document.getElementById('PaymentForm').onsubmit = function(e) {
		return false;
	};

	if($('#PaymentSuccessful').length > 0) { turnOffLight('PaymentSuccessful'); }
	if($('#PaymentError').length > 0) { turnOffLight('PaymentError'); }

	preload(
		"http://web.concernedjoe.com/Theme/Images/Early Access/paypalO.png",
		"http://web.concernedjoe.com/Theme/Images/Early Access/paypalI.png",
		"http://web.concernedjoe.com/Theme/Images/Early Access/paypalL.gif",
		"http://web.concernedjoe.com/Theme/Images/Download/DownloadWinO.png",
		"http://web.concernedjoe.com/Theme/Images/Download/DownloadMacO.png"
	);

	Itch.attachBuyButton(document.getElementById("PaypalButton"), {
		// replace the following with the correct information about your game
		user: "xelu",
		game: "concerned-joe-early-access"
	});

	$(".TipHover .fakelink").hover(function() {
		$('.TipContent').addClass("active");
	}, function() {
		$('.TipContent').removeClass("active");
	});
	
});